### ISSUE TITLE
Publish message text reversed when your messages are on the right side

### ISSUE THREAD

**Issue by SqueakyBeaver** [CorellanStoma/CreArts-Discord#10]
**Describe the bug**
When you enable the `src/bubbles/one` line in the theme.scss file, and you send a message in an announcements channel, the `share with your followers` message is reversed

**To Reproduce**
Steps to reproduce the behaviour:

1. Uncomment the `@use "src/bubbles/one";` in the root `theme.scss` file (if it is already commented)
2. Send a message in an announcement channel
3. Observe the `Share with your followers!` message

**Expected behaviour**
It looks like normal readable text

**Screenshots**
With bubbles on the right side:
![image](https://user-images.githubusercontent.com/63939550/123134443-642d6e00-d416-11eb-814a-2f534c8861cf.png)

Bubbles on the left:
![image](https://user-images.githubusercontent.com/63939550/123134468-6c85a900-d416-11eb-87aa-edc03783302a.png)

**Operating System:**
Windows 10

- Linux
- Windows
- macOS

**Additional context**
Might not show up all the time because there is a `Don't show this again` button next to the text

Edit: adding the below to my quick css seems to make it work, if that helps at all
```css
.container-2nXavw {
  transform: scaleX(-1) !important;
}
```

**Comment by CorellanStoma** [comment]
Should be fixed by the update v2.3.0.
Thanks for the report.
