### ISSUE TITLE
Top of server column section is not aligned with top row of items (server name, channel description, etc.)

### ISSUE THREAD

**Issue by FifiTheBulldog** [CorellanStoma/CreArts-Discord#5]
This could be a macOS-specific issue, but the tops of these are supposed to be aligned as far as I know.

<img width="676" alt="Screen Shot 2021-06-18 at 3 00 38 PM" src="https://user-images.githubusercontent.com/63314105/122605810-f5cb6300-d045-11eb-8a90-2e2a95b57960.png">

**Comment by CorellanStoma** [comment]
Should be fixed by the update v2.3.0.
