### ISSUE TITLE
"Plugins" header in user settings is too far down

### ISSUE THREAD

**Issue by FifiTheBulldog** [CorellanStoma/CreArts-Discord#6]
<img width="240" alt="Screen Shot 2021-06-18 at 3 09 23 PM" src="https://user-images.githubusercontent.com/63314105/122606586-2e1f7100-d047-11eb-8de1-d87ab7048a61.png">

**Comment by CorellanStoma** [comment]
Thanks for the report, should be fixed by the update v2.3.0.
